### ISSUE TITLE
Build script does not work on Windows

### ISSUE THREAD

**Issue by ghost** [krasimir/webpack-library-starter#1]
It seems that build script does not work on Windows. The following error occurred:

C:\0temp\webpack-library-starter>npm run build

> webpack-library-starter@0.1.2 build C:\0temp\webpack-library-starter
> WEBPACK_ENV=build webpack

'WEBPACK_ENV' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\Boris\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "run" "build"
npm ERR! node v4.2.1
npm ERR! npm  v3.3.10
npm ERR! code ELIFECYCLE
npm ERR! webpack-library-starter@0.1.2 build: `WEBPACK_ENV=build webpack`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webpack-library-starter@0.1.2 build script 'WEBPACK_ENV=build webpack'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the webpack-library-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     WEBPACK_ENV=build webpack
npm ERR! You can get their info via:
npm ERR!     npm owner ls webpack-library-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\0temp\webpack-library-starter\npm-debug.log

**Comment by krasimir** [comment]
Thanks. For reporting. I'll try reproducing it locally and it will be probably fixed.

**Comment by krasimir** [comment]
@dotVirgola problem solved. I just released a new version `0.1.3`.

![image](https://cloud.githubusercontent.com/assets/528677/12480826/d0e239dc-c04d-11e5-9153-f9445be0c0d5.png)

**Comment by llioor** [comment]
I have the same issue. I went through the instruction in your article but then I realized it is old.
I added last devDependencies as in the readme file.
I also tries to solve it with the package `"cross-env"`
Please update the article because it is very useful!
Thanks
