### ISSUE TITLE
npm test does not exit gracefully

### ISSUE THREAD

**Issue by aquaraga** [krasimir/webpack-library-starter#10]
### Steps to reproduce the issue: ###

1. Clone the repository
2. `npm install`
3. `npm build`
4. `npm test`

### Expected: ###

Tests pass and the process exits gracefully

### Actual: ###

Although the tests pass, you can see that the process does not exit. Looks like it is still running on a 'watch' mode, but I'm unable to find where it is specified (if at all).

It is important that `npm test` returns after running the tests, so that one could hook up these libraries to CI tools like Travis.

**Comment by nelsyeung** [comment]
If you look in the package.json file:
```json
"test": "mocha --compilers js:babel-core/register --colors -w ./test/*.spec.js"
```
The `-w` flag suggests watch mode, you can just remove that to stop it from happening and it will exit gracefully.

**Comment by krasimir** [comment]
@nelsyeung Thank you for clarification.
@aquaraga Exactly what @nelsyeung is saying. By default `npm run test` run `mocha` in a watch mode. I just disabled that and now `npm run test` runs the tests once and the process ends. While there is a new `npm run test:watch` that uses the watch mode.

P.S.
Version 0.2.0 released

**Comment by aquaraga** [comment]
Oh my bad. Thanks for the clarification
