### ISSUE TITLE
Why use --mode vs ENV

### ISSUE THREAD

**Issue by mikeerickson** [krasimir/webpack-library-starter#12]
Curious why you should to use a custom option `--mode` vs using the Node `ENV` (or `NODE_ENV`)   Surely not a deal breaker by any stretch, more just curious

**Comment by krasimir** [comment]
I think the environment variables are not working properly under Windows.

**Comment by mikeerickson** [comment]
Ahhh, I would not know that issue as I use Mac.  Makes good enough sense to me :)
