### ISSUE TITLE
Hi, will you update webpack to v2.* recently? Thanks

### ISSUE THREAD

**Issue by greedying** [krasimir/webpack-library-starter#13]
Thanks.

**Comment by mikeerickson** [comment]
This should be a simple conversion v1.x -> v2.x

If you want me to do a PR, I can knock it out today

**Comment by krasimir** [comment]
@mikeerickson that will be nice. I'll probably have time this weekend. So if it is not ready till then I'll jump on it.

**Comment by greedying** [comment]
@mikeerickson  @krasimir  Thanks

**Comment by mikeerickson** [comment]
@greedying @krasimir I will do it later this afternoon

**Comment by mikeerickson** [comment]
@krasimir In progress 👍

**Comment by krasimir** [comment]
Thanks

**Comment by mikeerickson** [comment]
@krasimir all done, creating PR shortly

**Comment by mikeerickson** [comment]
@krasimir All done, you can find [PR #14](https://github.com/krasimir/webpack-library-starter/pull/14)

**Comment by krasimir** [comment]
Merged and `0.2.2` released.
