### ISSUE TITLE
I get Library.js, not library.js

### ISSUE THREAD

**Issue by greedying** [krasimir/webpack-library-starter#15]
Thanks。

I git clone the project， and npm run build ,npm run dev。

then I get `Library.js`，`Library.min.js`, not the same as `library,js`, `library.min.js`

I dont know why。

In my options, all are `Library`, or  all are  `library`, it should not happen that both `Library` and `library` appear

**Comment by krasimir** [comment]
Feel free to change [this](https://github.com/krasimir/webpack-library-starter/blob/master/webpack.config.js#L8) line. It will affect the produced files.

**Comment by greedying** [comment]
yes, I know it. Just remind you the thing
