### ISSUE TITLE
Export alias on index.js (entry point)

### ISSUE THREAD

**Issue by iamrommel** [krasimir/webpack-library-starter#16]
How can i do the alias export on my entry point as shown in the image below

![image](https://cloud.githubusercontent.com/assets/177265/24859155/f10f0bda-1e21-11e7-8ebd-3d3fe0311fd3.png)

**Comment by krasimir** [comment]
I'm not sure that you can use `* as <something>`. I have the feeling that the problem is not in webpack but in that kind of exporting. Also the error that I see is about syntax.

**Comment by akkie** [comment]
Either you have to install [transform-export-extensions](https://babeljs.io/docs/plugins/transform-export-extensions/) and add it as plugin into your `.babelrc` file or you have to install [preset-stage-1](https://babeljs.io/docs/plugins/preset-stage-1/) and add it as preset into your `.babelrc` file.

**Comment by krasimir** [comment]
Thanks for the answer @akkie.
