### ISSUE TITLE
Fonts / Images

### ISSUE THREAD

**Issue by patrickdevivo** [krasimir/webpack-library-starter#22]
Apologies if this is naive, but can this handle font packing as well? Say I'm developing a react library that depends on a UI library such as https://github.com/palantir/blueprint or similar, which has fonts bundled with it.

How can I have webpack build those fonts and include them in my library?

**Comment by krasimir** [comment]
Hey, sorry I don't have experience bundling fonts. Isn't it better if they are loaded separately?

**Comment by krasimir** [comment]
Once you start using the starter you'll have a chance to modify the webpack config according to your needs. So I guess it is a matter of finding the right loader.
