### ISSUE TITLE
Having `<script>` tag usage issue

### ISSUE THREAD

**Issue by allenhwkim** [krasimir/webpack-library-starter#23]
First, thank for this example

In your article, http://krasimirtsonev.com/blog/article/javascript-library-starter-using-webpack-es6

It said 

> The library should:
> 
> * Be available for in-browser use. Understand including the library via <script> tag.

Thus, I tried this way, and  I am having error
```
<!DOCTYPE html>
<html>
<head>
  <script src="lib/Library.js"></script>
</head>
<body>
  <script>
  var cat = new Cat();
  console.log(cat.name);
  </script>
</body>
</html>
```

![image](https://user-images.githubusercontent.com/1437734/28551203-87c54c1c-70b4-11e7-8677-e7b8750bdc6a.png)

Am I missing any? or Is there any another way to make use of `<script>` tag?

**Comment by allenhwkim** [comment]
To resolve this issue, it seems I need to set window variable into index.js to make use of `<script>` tag. What do you think about this approach?

```
import Cat from './cat.js';
import Dog from './dog.js';
export { Dog, Cat };

window.Dog = Dog;  // <------------ This
window.Cat = Dat; // <------------ and this
```

**Comment by krasimir** [comment]
@allenhwkim That's weird because webpack should handle that use case. For example, every produced bundle starts with:
```js
(function webpackUniversalModuleDefinition(root, factory) {
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory();
	else if(typeof define === 'function' && define.amd)
		define("Library", [], factory);
	else if(typeof exports === 'object')
		exports["Library"] = factory();
	else
		root["Library"] = factory();
})(this, function() {
```
Where `root` is `this` and `this` is `window`. I think it's the way of how you export `Dog` and `Cat`. Can you try:

```js
import Cat from './cat.js';
import Dog from './dog.js';
export Dog;
export Cat;
```

**Comment by allenhwkim** [comment]
Thanks for the response.

separating export `Dog`, and `Cat` does not make any difference, I believe.

so the window exposured is not `Dog` or `Cat`, but `Libary`.
```
window.Library.Dog; // it works
window.Library.Cat;  // it works
window.Dog; //not works
window.Cat; //not works
```
Is this the proper way of using it?

**Comment by krasimir** [comment]
Well, yes. The idea of this repo is to build a library with a single entry point.

Best regards
