### ISSUE TITLE
Fork request: rollup

### ISSUE THREAD

**Issue by verlok** [krasimir/webpack-library-starter#24]
Hi,
I tried your starter and I find it amazing, and I also like your [article](http://krasimirtsonev.com/blog/article/javascript-library-starter-using-webpack-es6) with the full explanation.

This is exactly what I need to make my opensource library testable using ES6 modules, but I really don't like how webpack bundled things, it bloats the final code with a lot of unnecessary lines, whereas Rollup + Babel would only bundle and convert the ES6 code to ES5, then wrap it in the UMD definition.

I think that if you create a rollup-library-starter library it would become very popular. Can you do this? Can we do it together?

**Comment by iabw** [comment]
Possibly one of these boilerplates would fit your needs?

https://github.com/transitive-bullshit/react-modern-library-boilerplate
https://github.com/rollup/rollup-starter-lib
https://github.com/rollup/rollup-starter-app

If they don't, details about how they're lacking might be useful in either this ticket or in those repos.

**Comment by krasimir** [comment]
I don't have experience with rollup and will be happy to link such a project in the README here. So let me know if someone create a fork.
