### ISSUE TITLE
WARN babel-loader@7.0.0 requires a peer of webpack@2 but none is installed

### ISSUE THREAD

**Issue by briancodes** [krasimir/webpack-library-starter#26]
Running `npm install` gives the following warning:

`npm WARN babel-loader@7.0.0 requires a peer of webpack@2 but none is installed. You must install peer dependencies yourself.`

Should we be seeing this warning given that "webpack": "3.1.0"` is being used. Not sure if I need to change the webpack version or the babel-loader?

Using Node v8.9.0, npm v5.5.1 on Windows

**Comment by krasimir** [comment]
I just updated the dependencies and added `yarn` to the game. You shouldn't see that warning anymore. (version `1.0.0`)

**Comment by briancodes** [comment]
Ok great, I'll check that out.
