### ISSUE TITLE
about babel plugin.

### ISSUE THREAD

**Issue by yuu2lee4** [krasimir/webpack-library-starter#30]
babel-plugin-add-module-exports is unnecessary in project base on webpack3,i think babel-plugin-transform-runtime need be added.

**Comment by krasimir** [comment]
Just update the starter to use the latest babel. The plugins that I needed to add are just:
```
"plugins": [
  "@babel/plugin-proposal-class-properties",
  "babel-plugin-add-module-exports",
  "@babel/plugin-transform-classes"
]
```
