### ISSUE TITLE
Webpack 4 incompatible

### ISSUE THREAD

**Issue by ghost** [krasimir/webpack-library-starter#35]
When upgrading to the new Webpack, there is this error:

`Error: webpack.optimize.UglifyJsPlugin has been removed, please use config.optimization.minimize instead.`

**Comment by pmunin** [comment]
I created separate fork with the solution for wp4: https://github.com/pmunin/webpack-library-starter

**Comment by manelclos** [comment]
this was done here https://github.com/krasimir/webpack-library-starter/commit/492358aad2a07df5557bc9209c0a3fe7780c154c

issue can be closed

**Comment by krasimir** [comment]
This started is now migrated to webpack 5.
