### ISSUE TITLE
Intellisense doesn’t work after transpiled

### ISSUE THREAD

**Issue by GabrielBB** [krasimir/webpack-library-starter#36]
Great starter, it really helped me a lot. I just have one problem with it, intellisense work well with my JS file under src, but when i build it, the file generated under lib folder doesn’t. It’s like you’re working with classes that are not exported but they are, since, as I said, they are showing when not transpiled. I was reading about Typescript Declaration Files so my code is well documented and intellisense work properly, but I see a lot of libraries on GitHub without that file. Is something missing for this to properly work or that’s the normal behavior of UMD libraries?

**Comment by krasimir** [comment]
I think the Intellisense is a feature of your editor. Has nothing to do with how the library is exported. In general you shouldn't change the files in the `lib` folder but only those in `src`.

**Comment by GabrielBB** [comment]
You're right. I just created a Typescript Declaration File, placed it in lib/ and included it in the package json like:
```
{
    "name": "Iron Man Software",
    "author": "Tony Stark",
    "version": "3.0.0",
    "main": "./lib/extension.js",
    "types": "./lib/declarations.ts"
}
```

Intellisense worked on Visual Studio Code after that.
