### ISSUE TITLE
How to use RequireJS client-side to load the Cat & Dog modules

### ISSUE THREAD

**Issue by CodeRedPaul** [krasimir/webpack-library-starter#42]
Hi there

I have successfully loaded and run the bundled file in the following contexts:
- Directly in the browser via both
-- a <script> tag
-- dynamically via JavaScript e.g. document.createElement('script').
- Using the SystemJS module loader

However, I can't seem to work out how to use an AMD loader to do the same. RequireJS is meant to support AMD but I've been wracking my brains (and the internet) trying to make it work...

Can anyone give any advice on how to consume the out-of-the-box bundle with the Cat and Dog examples via RequireJS, please?

Thanks so much,

Paul

**Comment by krasimir** [comment]
@CodeRedPaul in this commit fbb7ac9 I'm adding a support of AMD export with `yarn build` and `yarn dev-amd`. An example of how to use the exported files with requirejs could be seen here https://github.com/krasimir/webpack-library-starter/blob/master/lib/requirejs.html

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js"></script>
    <script src="./webpack-library-starter.amd.min.js"></script>
    <script>
      requirejs(["webpack-library-starter.amd"], function (lib) {
        const d = new lib.Dog();
        console.log(d.name);
      });
    </script>
  </body>
</html>
```
