### ISSUE TITLE
Launch dev server for index.html consuming the dev library

### ISSUE THREAD

**Issue by manelclos** [krasimir/webpack-library-starter#44]
It would be super useful for development, currently I'm using webpack-dev-server manually.

**Comment by ghost** [comment]
Here's what I've done:

Add these devDependencies:
``` bash
npm i --D webpack-dev-server html-webpack-plugin
```

Then in `package.json`, change `scripts.dev` to: `"webpack-dev-server --progress --colors --watch --env dev"`

Finally, in `webpack.config.js` add the following:

```js
const webpack = ...
...
const HTMLWebpackPlugin = require('html-webpack-plugin')

const config = {
...
  plugins: [
    new HTMLWebpackPlugin({
      template: 'src/sandbox.html'
    })
  ],
...
}
```

That will load `src/sandbox.html` and inject it with your entry script.

**Comment by manelclos** [comment]
This worked great, thanks!
