### ISSUE TITLE
transpiling to ES2015? Have a potential solution.

### ISSUE THREAD

**Issue by Andriy-Kulak** [krasimir/webpack-library-starter#48]
Hi I noticed that if I used async/await or other ES2016 features, then the tests would not recognize the code and fail for various reasons so I assume it wasn't transpiled properly to ES2015.

My solution was to add `babel-pollyfill` (currently "^6.26.0") as a dependency and adjust the entry point in `webpack.config.js` to  
```js
const config = {
  // ...
  entry: ['babel-polyfill', __dirname + '/src/index.js'],
  // ...
}
```

``

As a result something like below now works well. Is this a good solution in people's opinion?  I got idea from here: https://github.com/babel/babel-loader/issues/249
```js
const wait = async (ms) => (new Promise((resolve) => { setTimeout(resolve, ms) }))

const sdk = async () => {
  await wait(2000);
  return '111111111111'
}
export { Dog, Cat, sdk };
```

**Comment by krasimir** [comment]
I migrated the starter to use `jest` and `jest-babel` so you shouldn't experiencing this problem.
