### ISSUE TITLE
Conceptual doubt if using this project applies to my problem

### ISSUE THREAD

**Issue by ramuyk** [krasimir/webpack-library-starter#58]
Hi

I've been struggling with a problem for a while and I've tried to use this project to solve it (although unsuccessfully so far). I'd like to know if what I have in mind is possible before spending much more energy on it...

Context:

I have a project where I use [deck.gl](https://deck.gl/) to create web maps. It works fine, however, I need the functionality of drawing polygons and for that the deck.gl documentation tells me to use [nebula.gl](https://nebula.gl/). The sample of the functionality that I need can be found here: https://codesandbox.io/s/deckgl-and-nebulagl-editablegeojsonlayer-no-react-p9yrs?file=/app.js

The problem:

The problem that I have is that on the nebula.gl documentation there's no library compiled to be used on a `<script>` tag. They only work with the library installed through npm or yarn, then the only way I managed to make it work so far was by compiling the entire project...

My question:

I've read this page: https://krasimirtsonev.com/blog/article/javascript-library-starter-using-webpack-es6 before arriving here on Github. My doubt is: since you're saying on your blog that's possible to compile an individual javascript library, do you think it'd be possible to compile this nebula.gl library in a single file just so I can successfully use it on a `<script>` tag while serving this file on my own server? Even though I've tried to compile the nebula.gl library I didn't manage to do that, I reached a point that I don't know if what I'm trying to do makes sense since on the nebula.gl documentation I don't find much information about it.

**Comment by krasimir** [comment]
Hey @rafaelmuynarsk,

what's the problem of compiling the project and having a bundle that you can import via script tag?

I had a similar case like yours with babel. I would suggest to search for an online playground that includes nebula.gl and get the client-side version of the library from there.

**Comment by ramuyk** [comment]
Hi @krasimir

I've been thinking for a while about this problem... I'm in a very specific case since I'm dealing with a [Node-RED project](https://nodered.org/) that's very close to a Vanilla Javascript project. At first, I wanted to avoid using bundle solutions to the project, but when you say having a bundle that I can import via the script tag you mean having a bundle of all Javascript code from the project, right? I think this will work fine for me although I'll need to change some stuff in the way that the project is made. 

When I made this question I was trying to avoid using a bundle of the entire project to solve this problem and I wanted to create a bundle of a single library. But now I think that having a bundle of the project will work for my case as well. 

Thanks for the response!
