### ISSUE TITLE
Yeoman generator

### ISSUE THREAD

**Issue by Toub** [krasimir/webpack-library-starter#8]
Good stuff. What about creating a yeoman generator for this starter?

**Comment by krasimir** [comment]
That's a good idea. I'll appreciate a PR since I don't have experience using Yeoman.

**Comment by mikeerickson** [comment]
@Toub @krasimir While it would be "neat" I don't see the benefit of creating a generator?  
A simple `git clone` will more than suffice?

**Comment by Toub** [comment]
With a generator, you can customize the name of the module, and also add some options.

It is also easier to use as you have it in your "yeoman" toolbox (don't have to remember the project url) and give a better visibility to the project as it is referenced in yeoman.

**Comment by krasimir** [comment]
If someone is interested for creating a `yeoman` generator and keen to create a PR  please post here. Closing for now.
