### ISSUE TITLE
external dependencies

### ISSUE THREAD

**Issue by riskers** [krasimir/webpack-library-starter#9]
Now, I have a library `xx` depending `jQuery`:

```js
import $ from 'jquery'

...
```

I find #3 , so I write this externals:

```js
externals: {
    'jquery': 'jQuery'
}
```

It's great! The bundle file is small!

But, when I use my library:

```js
var xx = require('xx')
```

then use webpack, the library put `xx` and `jQuery` together. I don't know how to separate them?

**Comment by krasimir** [comment]
Sorry for the late reply. Is there `require('jquery')` inside your library. If yes, then this result is correct.

**Comment by adamkleingit** [comment]
So the library will be bundled together with all its dependencies?
For example if I have `import 'angular'` then angular will be bundled with my library?
Is there a way to bypass this?

Thanks

**Comment by krasimir** [comment]
@adamkleingit the proper way for handling this case is [webpack's externals](https://webpack.github.io/docs/library-and-externals.html#applications-and-externals).

@riskers Now, when I'm reading your question again I think I understood what's going on. Correct me if I'm wrong but you build your library using webpack and then you have a build step (again using webpack) that uses your library. If that's the case then you'll have to use `externals` option one more time in your build process.

**Comment by gen4sp** [comment]
But how to include dependencies into your library? 
If I use something like `import _  from "lodash"` it generate an error while building
`Module not found: Error: Can't resolve 'lodash' in...`
Once I include lodash in `externals` option it builds perfectly, but library needs lodash as dependency.
Thanks!

**Comment by gen4sp** [comment]
Oh, solution found
`modules: [path.resolve('./src'), path.join(__dirname, 'node_modules')],`

**Comment by freeman29** [comment]
@gen4sp I've tried your solution above on including dependencies but it's not working correctly because it's  now looking for all its dependencies.

I'm trying to include request library.

**Comment by freeman29** [comment]
I resolved my issue by adding the following into the config object:

```target: 'node'```

a good read from [jlongster blog](http://jlongster.com/Backend-Apps-with-Webpack--Part-I)

**Comment by krasimir** [comment]
@riskers do we have to keep the issue open?
